### ISSUE TITLE
Spring Framework 6 (Spring Boot 3) support

### ISSUE THREAD

**Issue by Crovitz** [zalando/problem#437] opened 2022-11-25 13:50 UTC
Due to the release of the new Spring Boot 3, there is a need for zalando problem support.

## Detailed Description
I'm trying invoke some requests which should be handled by Advice Trail but I receive when I want to return http 404:
```
java.lang.NoSuchMethodError: 'org.springframework.http.ResponseEntity$BodyBuilder org.springframework.http.ResponseEntity.status(org.springframework.http.HttpStatus)'
	at org.zalando.problem.spring.web.advice.AdviceTrait.lambda$create$0(AdviceTrait.java:133) ~[problem-spring-web-0.27.0.jar:na]
```
On Spring Boot 2.x.x version everything works as expected.

## Possible Implementation
I'm not sure if it will be easy to handle it, because Spring Framework 6 base on Jakarta instead of Javax and there were be some relevant changes.

## Your Environment
* Version used: `problem-spring-web-0.27.0`

**Comment by hantsy** [comment] 2022-11-28 07:32
Spring 6 includes a built-in Problem Details implementation. Hope this project will fill some blank of the official exception handler, eg. better Bean validation handling etc.

**Comment by MALPI** [comment] 2023-02-09 08:12
Hey @hantsy thanks for your response. Do you have any particular suggestions?

**Comment by Crovitz** [comment] 2023-02-09 08:29
@MALPI your:
- ControllerAdvice should extend `ResponseEntityExceptionHandler`
- Exception should extend `ErrorResponseException`
- and for `ErrorResponseException` you need to build ProblemDetail eg. `ProblemDetail.forStatusAndDetail(status, message)`

**Comment by HJK181** [comment] 2023-02-20 13:08
Any updates on this? Our migration to Spring Boot 3 is blocked as we use zalando problem in all our modules ...

**Comment by Crovitz** [comment] 2023-02-20 13:26
Spring Boot 3 has their own implementation of the RFC7323, you have to adapt Spring's implementation.

**Comment by hantsy** [comment] 2023-02-21 01:50
> Hey @hantsy thanks for your response. Do you have any particular suggestions?

Refactor to use Spring built-in Problem APIs, add the missing part in the Spring Boot, such as Bean validation error collection, security exception improvement.

**Comment by edwardmp** [comment] 2023-06-23 12:53
I personally think this libraries syntax is a bit nicer to use than the Spring one, so would be really nice if this library supports Spring Boot 3

**Comment by MALPI** [comment] 2023-09-02 06:36
Hey, 

First of all, I think this issue is a duplicate of https://github.com/zalando/problem-spring-web/issues/817.

In addition we released https://github.com/zalando/problem-spring-web/releases/tag/0.29.1 which is supporting Spring Boot 3.

I would therefore close the issue for now.

In case anything is unclear please let me know.

Best,

Malte

**Closed by MALPI** 2023-09-02 06:36 UTC
Labels: Feature

**Comment by hantsy** [comment] 2023-10-11 07:26
@MALPI It is based on the Spring 6 Problem APIs?
